[package]
name = "drone-target"
version = "0.1.0"
authors = ["Nikita Zemtsov <z-nik@ya.ru>"]
edition = "2018"


[dependencies.dotrix]
git = "https://github.com/lowenware/dotrix"
rev = "72f8ba980cfa25cf6eab20460586e66de3e7a819"

[dependencies.rapier3d]
version = "0.7.2"
features = [ "simd-stable" ]
