[package]
name = "drone-target"
version = "0.1.0"
authors = ["Nikita Zemtsov <z-nik@ya.ru>"]
edition = "2018"


[dependencies.dotrix]
git = "https://github.com/lowenware/dotrix"
rev = "0cf5335840b21e4d80ce0b62f64ef54903d28dd2"

[dependencies.rapier3d]
version = "0.7.2"
features = [ "simd-stable" ]
